- .travis.yml
> Add travis keys

- build.gradle
> Gradle changes

- build.gradle
> Gradle task updated.

- build.gradle
- src/main/java/uk/gov/hmcts/payment/processors/PbaCsvReportProcessor.java
> PAY-2828:Added Webjob configuration for FPL

- src/main/java/JobProcessorApplication.java
- src/main/java/uk/gov/hmcts/payment/processors/BarCsvReportProcessor.java
- src/main/java/uk/gov/hmcts/payment/processors/CardCsvReportProcessor.java
- src/main/java/uk/gov/hmcts/payment/processors/PbaCsvReportProcessor.java
- src/main/java/uk/gov/hmcts/payment/processors/PbaFinremWeeklyCsvReportProcessor.java
- src/main/java/uk/gov/hmcts/payment/processors/StatusUpdateProcessor.java
- src/main/java/uk/gov/hmcts/payment/s2s/S2STokenGeneration.java
> PAY-2828:Added comments for all the web jobs

- build.gradle
> PAY-2828:Upgraded gradle version

- charts/payment-jobs/.helmignore
- charts/payment-jobs/Chart.yaml
- charts/payment-jobs/requirements.yaml
AB#846
Updated chart
```
[ ] Yes
[x] No
```
> Updated chart

- charts/payment-jobs/Chart.yaml
- charts/payment-jobs/values.yaml
AB#846
Updated chart
```
[ ] Yes
[x] No
```
> Updated chart values

- build.gradle
- config/owasp/suppressions.xml
> CVE Fixed for CVE-2016-5394 & CVE-2016-6798

- build.gradle
- charts/payment-jobs/Chart.yaml
> updated chard job version

- charts/payment-jobs/Chart.yaml
- config/owasp/suppressions.xml
> Update suppressions.xml - extend cve suppressions

- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/payment/processors/JobProcessorFactory.java
- src/main/java/uk/gov/hmcts/payment/processors/UnprocessedPaymentUpdateProcessor.java
- src/test/java/uk/gov/hmcts/payment/processors/UnprocessedPaymentUpdateProcessorTest.java
> unprocessed-payment-update job

- src/main/java/uk/gov/hmcts/payment/processors/JobProcessorFactory.java
- src/main/java/uk/gov/hmcts/payment/processors/UnprocessedPaymentUpdateProcessor.java
- src/test/java/uk/gov/hmcts/payment/processors/UnprocessedPaymentUpdateProcessorTest.java
> Pay 5658 merge

- config/owasp/suppressions.xml
> update date in suppression file

- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/payment/processors/PbaCsvReportProcessor.java
- src/test/java/uk/gov/hmcts/payment/processors/PbaCsvReportProcessorTest.java
> added family private law pba report

- README.md
- build.gradle
- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/payment/processors/PbaCsvReportProcessor.java
- src/test/java/uk/gov/hmcts/payment/processors/PbaCsvReportProcessorTest.java
> added changes to scheduled jobs for iac pba report

- build.gradle
- charts/payment-jobs/Chart.yaml
- charts/payment-jobs/values.yaml
- config/owasp/suppressions.xml
> added refunds url and upgraded chart version

- charts/payment-jobs/Chart.yaml
> Update Chart job version in Chart.yaml

- Dockerfile
- charts/payment-jobs/Chart.yaml
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/PAY-4884
Update dockerfile java ref and suppressions extend date.
```
[ ] Yes
[x] No
```
> PAY-4884: Updated Dockerfile, suppressions

- charts/payment-jobs/Chart.yaml
- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/payment/processors/DuplcatePaymentProcessor.java
- src/main/java/uk/gov/hmcts/payment/processors/JobProcessorConfiguration.java
- src/main/java/uk/gov/hmcts/payment/processors/JobProcessorFactory.java
- src/main/java/uk/gov/hmcts/payment/processors/PbaCsvReportProcessor.java
- src/test/java/uk/gov/hmcts/payment/processors/DuplicatePaymentProcessorTest.java
> Duplicatepayment 2

- charts/payment-jobs/Chart.yaml
- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/payment/processors/DuplcatePaymentProcessor.java
- src/main/java/uk/gov/hmcts/payment/processors/JobProcessorFactory.java
- src/main/java/uk/gov/hmcts/payment/processors/PbaCsvReportProcessor.java
- src/test/java/uk/gov/hmcts/payment/processors/DuplicatePaymentProcessorTest.java
> test add whitespace

- .github/workflows/ci.yml
- Dockerfile
- build.gradle
- config/owasp/suppressions.xml
- gradle/wrapper/gradle-wrapper.properties
PAY-6397: Scheduled Jobs Upgrades
[PAY-6397] (https://tools.hmcts.net/jira/browse/PAY-6397).
> PAY-6397: Scheduled Jobs Upgrades

- .github/renovate.json
> rennovate fix added

- charts/payment-jobs/Chart.yaml
- charts/payment-jobs/values.yaml
PAY_6611
Version update
- [ x ] Does this PR introduce a breaking change
> version update

- charts/payment-jobs/Chart.yaml
- config/owasp/suppressions.xml
- cve-resolution-strategy.gradle
https://tools.hmcts.net/jira/browse/PAY-6023
extend the date of the supressions, just to get a build going
> extend date

- charts/payment-jobs/Chart.yaml
PAY-6757: Scheduled Jobs Upgrades
[PAY-6757] (https://tools.hmcts.net/jira/browse/PAY-6757).
> PAY-6757: Scheduled Jobs Upgrades

- Jenkinsfile_nightly
- config/owasp/suppressions.xml
> Add nightly pipeline

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/PAY-6296
> PAY-6296: Fix CVE-2022-1471

- charts/payment-jobs/Chart.yaml
- charts/payment-jobs/values.yaml
> Fix secret ref

- charts/payment-jobs/Chart.yaml
- docker-compose.yml
- src/main/java/uk/gov/hmcts/payment/processors/PbaCsvReportProcessor.java
https://tools.hmcts.net/jira/browse/PAY-6820
Adding Specified Money Claims to PBA Report
> PAY-6820: Adding Specified Money Claims to PBA Report

- build.gradle
- config/owasp/suppressions.xml
- cve-resolution-strategy.gradle
https://tools.hmcts.net/jira/browse/PAY-7124
PAY-7124: Address High Vulnerabilities
> PAY-7124: Address High Vulnerabilities

- build.gradle
Reverting back to v9 as v10 has breaking changes
> Revert "Update plugin org.owasp.dependencycheck to v10"

- build.gradle
https://tools.hmcts.net/jira/browse/PAY-7231
Fix Scheduled Jobs
> PAY-7231: Revert owasp library to fix pipeline

- build.gradle
https://tools.hmcts.net/jira/browse/PAY-7244
Update to use available groovy-xml library.
> PAY-7244: Update to use available groovy-xml lib

- .github/workflows/ci.yml
- src/main/java/uk/gov/hmcts/payment/processors/DuplicatePaymentProcessor.java
- src/main/java/uk/gov/hmcts/payment/processors/JobProcessorFactory.java
- src/test/java/uk/gov/hmcts/payment/JobProcessorRunnerTest.java
- src/test/java/uk/gov/hmcts/payment/processors/DuplicatePaymentProcessorTest.java
- src/test/java/uk/gov/hmcts/payment/processors/JobProcessorFactoryTest.java
https://tools.hmcts.net/jira/browse/PAY-5978
Adds a duplicate payment report process
Tested with PAY-5978 Payment APP update in DEMO.
> PAY-5978: Update schedule for duplicate-payment-process

- Dockerfile
- Jenkinsfile_nightly
- build.gradle
- config/fortify-client.properties
PAY-7444: Scheduled Jobs Upgrades to run fortify
[PAY-7444] (https://tools.hmcts.net/jira/browse/PAY-7444).
> PAY-7444: Scheduled Jobs Upgrades to run fortify

- build.gradle
https://tools.hmcts.net/jira/browse/PAY-7625
This is part of the BAR PBA Report cleanup, but the original PR although passing in the PR pipeline, it failed in master.
Reproduced issue locally, and the problem was fixed. So long at the PR and master passes, it should be fine.
> PAY-7625: Align version of test libraries

- build.gradle
Reverts hmcts/ccpay-scheduled-jobs#176
> Revert "Update dependency org.junit.jupiter:junit-jupiter to v5.12.0"

- build.gradle
See [PAY-7740](https://tools.hmcts.net/jira/browse/PAY-7740)
use maven bom for spring
Tested as part of pipeline
> PAY-7740 pipeline fixes

- build.gradle
- jitpack.yml
https://tools.hmcts.net/jira/browse/CME-529
Replace jitpack with azure
> CME-529 replace jitpack with azure

- build.gradle
- config/owasp/suppressions.xml
> Address CVE-2025-48976
